server:
  port: 8081

spring:
  application:
    name: user-service
  data:
    mongodb:
      uri: mongodb://${MONGO_ROOT_USER}:${MONGO_ROOT_PASSWORD}@localhost:27017/${MONGO_DB}?authSource=admin
      auto-index-creation: true

application:
  security:
    jwt:
      secret-key: ${TOKEN_SECRET_KEY}
      expiration-time: ${TOKEN_EXPIRATION_TIME}
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{correlationId}] %-5level %logger{36} - %msg%n"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/